### ISSUE TITLE
the trouble about wget 

### ISSUE THREAD

**Issue by woaixueyingying** [DeepSportradar/instance-segmentation-challenge#2]
It is not work ,When I download the dataset with this command,wget  https://arena-data.keemotion.com/tmp/gva/mmsports_challenge_set_data.zip.Also,I download that with this command curl -O -L https://arena-data.keemotion.com/tmp/gva/mmsports_challenge_set_data.zip.But it shows an invalid file.How to solve this problem?

**Comment by woaixueyingying** [comment]
Could you put the challenge data set on Google Drive for participants to download? @mistasse

**Comment by mistasse** [comment]
Sorry for the inconvenience. Indeed, it seems like the link is dead. I will try to have it fixed next week!

**Comment by woaixueyingying** [comment]
OK,thanks.

**Comment by mistasse** [comment]
Hi! I have tried to rebuild the file and put it back in place. I haven't tried yet if everything was working as expected because I don't have much time, but it should do it in my opinion.
Please don't hesitate to keep me tuned, I should be able to allocate more time next week if needed.

**Comment by woaixueyingying** [comment]
Thank you.I have downloaded it, and it's complete.
