### ISSUE TITLE
multiple GPUs

### ISSUE THREAD

**Issue by woaixueyingying** [DeepSportradar/instance-segmentation-challenge#4]
If I want to run the program on multiple GPUs, how do I do that?

**Comment by mistasse** [comment]
Hi, based on the MMDet 3.X documentation: https://mmdetection.readthedocs.io/en/latest/user_guides/tracking_train_test.html#train-on-single-node-multiple-gpus.
You should download the `tools/dist_train.sh` file from MMDet and use it: https://github.com/open-mmlab/mmdetection/blob/main/tools/dist_train.sh.

**Comment by woaixueyingying** [comment]
Thanks,I get it.And  I want to know,will the rankings of the first Phase  challenge datasets be published？

**Comment by mistasse** [comment]
They have been published on Discord ;-)
