### ISSUE TITLE
Is this competition still going on? 

### ISSUE THREAD

**Issue by HYheyue** [DeepSportradar/instance-segmentation-challenge#5]
Because I see there have been no new submissions for a long time.

**Comment by HYheyue** [comment]
and when will the challenge track be released?

**Comment by mistasse** [comment]
Yes, the challenge is still running, the second phase will close on October, 20 as mentioned on http://mmsports.multimedia-computing.de/mmsports2023/challenge.html .
The challenge set is the same as for the previous phase, we will however soon increase the number of submission attempts.

**Comment by HYheyue** [comment]
Hello, can i know the om score of the first place?

**Comment by HYheyue** [comment]
> Yes, the challenge is still running, the second phase will close on October, 20 as mentioned on http://mmsports.multimedia-computing.de/mmsports2023/challenge.html . The challenge set is the same as for the previous phase, we will however soon increase the number of submission attempts.

Hello, can i know the om score of the first place?
